//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RivicSystems_AspNetMvcDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestProfessors
    {
        public string Professor_Name { get; set; }
        public string Professor_Country { get; set; }
        public int Awarded_Year { get; set; }
    }
}
