//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RivicSystems_WcfConsumerDemo.StudentServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentServiceReference.IStudentService")]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/Enroll", ReplyAction="http://tempuri.org/IStudentService/EnrollResponse")]
        string Enroll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/Enroll", ReplyAction="http://tempuri.org/IStudentService/EnrollResponse")]
        System.Threading.Tasks.Task<string> EnrollAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/RegisterForCourse", ReplyAction="http://tempuri.org/IStudentService/RegisterForCourseResponse")]
        string RegisterForCourse(string courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/RegisterForCourse", ReplyAction="http://tempuri.org/IStudentService/RegisterForCourseResponse")]
        System.Threading.Tasks.Task<string> RegisterForCourseAsync(string courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GenerateException", ReplyAction="http://tempuri.org/IStudentService/GenerateExceptionResponse")]
        int GenerateException(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GenerateException", ReplyAction="http://tempuri.org/IStudentService/GenerateExceptionResponse")]
        System.Threading.Tasks.Task<int> GenerateExceptionAsync(int num1, int num2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : RivicSystems_WcfConsumerDemo.StudentServiceReference.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<RivicSystems_WcfConsumerDemo.StudentServiceReference.IStudentService>, RivicSystems_WcfConsumerDemo.StudentServiceReference.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Enroll() {
            return base.Channel.Enroll();
        }
        
        public System.Threading.Tasks.Task<string> EnrollAsync() {
            return base.Channel.EnrollAsync();
        }
        
        public string RegisterForCourse(string courseId) {
            return base.Channel.RegisterForCourse(courseId);
        }
        
        public System.Threading.Tasks.Task<string> RegisterForCourseAsync(string courseId) {
            return base.Channel.RegisterForCourseAsync(courseId);
        }
        
        public int GenerateException(int num1, int num2) {
            return base.Channel.GenerateException(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> GenerateExceptionAsync(int num1, int num2) {
            return base.Channel.GenerateExceptionAsync(num1, num2);
        }
    }
}
